# Generated by Django 2.1 on 2019-07-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_per_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='per',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
