# Generated by Django 2.1 on 2019-07-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_per_common'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pword', models.CharField(max_length=30)),
                ('emil', models.CharField(max_length=30)),
            ],
        ),
    ]
